language: go

go:
  - 1.13.3

before_install:
  - go mod download
  - go mod tidy

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)